### ISSUE TITLE
Design: Maybe rethinl hover colors on touch devices

### ISSUE THREAD

**Issue by Greenheart** [Greenheart/idg.tools#216]
For touch devices, we could possibly disable background colors that change on hover. This is based on user feedback that it was a bit unclear which skills in the `SkillTabs` that were selected or not. Especially on mobile.

**Comment by Greenheart** [comment]
This will get solved once we migrate to Tailwind version 4 which wraps hover styles in a media query

```css
@media (hover: hover) {
  button:hover {
    border: 3px solid green; /* solves sticky problem */
  }
}
```
